apiVersion: azure.caas.upbound.io/v1alpha1
kind: Cluster
metadata:
  name: azure-spoke-02
  namespace: default
  annotations:
    uptest.upbound.io/pre-delete-hook: ../testhooks/azure-release-delete.sh
spec:
  parameters:
    id: azure-spoke-02
    region: West US
    version: "1.27.3"
    nodes:
      count: 3
      instanceType: Standard_B2s
    gitops:
      url: https://github.com/upbound/caas-cluster-configuration
  writeConnectionSecretToRef:
    name: azure-spoke-02-kubeconfig
