apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xcontrolplanes.mcp.caas.upbound.io
spec:
  writeConnectionSecretsToNamespace: upbound-system
  compositeTypeRef:
    apiVersion: mcp.caas.upbound.io/v1alpha1
    kind: XControlPlane
  mode: Pipeline
  pipeline:
  - step: xcontrolplane
    functionRef:
      name: upbound-configuration-caasxcontrolplane
  - step: crossplane-contrib-function-auto-ready
    functionRef:
      name: crossplane-contrib-function-auto-ready
