apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xconnectors.mcp.caas.upbound.io
spec:
  writeConnectionSecretsToNamespace: upbound-system
  compositeTypeRef:
    apiVersion: mcp.caas.upbound.io/v1alpha1
    kind: XConnector
  mode: Pipeline
  pipeline:
  - step: xconnector
    functionRef:
      name: upbound-configuration-caasxconnector
  - step: crossplane-contrib-function-auto-ready
    functionRef:
      name: crossplane-contrib-function-auto-ready
