apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xclusters.caas.upbound.io
spec:
  writeConnectionSecretsToNamespace: upbound-system
  compositeTypeRef:
    apiVersion: caas.upbound.io/v1alpha1
    kind: XCluster
  mode: Pipeline
  pipeline:
  - step: xcluster
    functionRef:
      name: upbound-configuration-caasxcluster
  - step: crossplane-contrib-function-auto-ready
    functionRef:
      name: crossplane-contrib-function-auto-ready
